export const projects = [
  {
    title: "Solvemeet - Consultation Platform",
    category: "Frontend Web & Mobile Application",
    color: "bg-pink-900/20 bg-backdrop-blur-md",
    description:
      "A consultation-based platform connecting users with advisors through real-time communication. Implemented Socket.io for audio/video calls and chat functionality, enabling seamless interactions between clients and advisors across various professions.",
    image: "/portfolio/solvemeet.png",
    technologies: ["React Native", "Next.js", "Node.js", "Socket.io", "Tailwind CSS"],
    link: "https://www.solvemeet.com/",
    features: [
      "Real-time audio/video calling with Socket.io",
      "Instant messaging system",
      "Advisor profile management",
      "Secure payment integration",
      "Responsive mobile and web interfaces",
    ],
    role: "Full Stack Developer",
    impact: "Launched platform serving thousands of users seeking professional advice",
  },
  {
    title: "Risus - Social media Platform",
    category: "Frontend mobile Application",
    color: "bg-pink-950/95 bg-backdrop-blur-xl",
    description:
      "Developed a dynamic social media platform where users can create profiles, post, like, comment, share, follow others, and chat in real-time, enhancing social connectivity and engagement. Built using React Native with Google Login integration for seamless authentication and REST API integration for data handling. Additionally, implemented AI-powered image generation for posts and a coin-based reward system to boost user interaction and retention.",
    image: "/portfolio/advisor2.png",
    technologies: ["React Native", "Stripe", "Rest API"],
    link: "",
    features: [
      "Product browsing and filtering",
      "Shopping cart with real-time updates",
      "Secure Stripe payment integration",
      "Order tracking and management",
      "Responsive mobile app and website",
      "ERP integration with Odoo",
    ],
    role: "Frontend Developer",
    impact: "Successfully launched mobile app and website with 1000+ products",
  },
  {
    title: "Wemasomo - NGO Health & Education Platform",
    category: "Full-Stack Web Application",
    color: "bg-black/90 bg-backdrop-blur-xl",
    description:
      "Built a comprehensive platform for an NGO focused on female health and education. Features AI-powered assistance, graphical content, and videos to support users in accessing health and educational resources.",
    image: "/portfolio/wemasomo-1.png",
    technologies: ["Next.js", "Firebase", "Tailwind CSS", "AI Integration", "React"],
    link: "https://wemasomo.com",
    features: [
      "Comprehensive topic descriptions with images and videos",
      "AI-powered user assistance",
      "Responsive design for all devices",
      "Content management system",
      "User engagement tracking",
    ],
    role: "Frontend Developer",
    impact: "Launched platform serving thousands of users with health and education resources",
  },
  {
    title: "EastGold - Investment Platform",
    category: "Frontend Mobile Application",
    color: "bg-fuchsia-950/95 bg-backdrop-blur-xl",
    description:
      "Created a premium investment platform for gold products with sophisticated UI/UX and smooth animations. Ensures seamless user interactions, secure transactions, and efficient investment oversight.",
    image: "/portfolio/eastgold2.png",
    technologies: ["React.js", "Tailwind CSS", "GSAP", "Responsive Design"],
    link: "#",
    features: [
      "Elegant product showcase",
      "Smooth GSAP animations",
      "Fully responsive design",
      "Product detail pages with zoom",
      "Contact form integration",
    ],
    role: "Frontend Developer",
    impact: "Built visually stunning website with excellent performance",
  },
]
